-- AlterTable
ALTER TABLE `directitems` ADD COLUMN `field10` VARCHAR(191) NULL,
    ADD COLUMN `field6` VARCHAR(191) NULL,
    ADD COLUMN `field7` VARCHAR(191) NULL,
    ADD COLUMN `field8` VARCHAR(191) NULL,
    ADD COLUMN `field9` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `directreturnitems` ADD COLUMN `field10` VARCHAR(191) NULL,
    ADD COLUMN `field6` VARCHAR(191) NULL,
    ADD COLUMN `field7` VARCHAR(191) NULL,
    ADD COLUMN `field8` VARCHAR(191) NULL,
    ADD COLUMN `field9` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `stock` ADD COLUMN `field10` VARCHAR(191) NULL,
    ADD COLUMN `field6` VARCHAR(191) NULL,
    ADD COLUMN `field7` VARCHAR(191) NULL,
    ADD COLUMN `field8` VARCHAR(191) NULL,
    ADD COLUMN `field9` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `stockreportcontrol` ADD COLUMN `field10` VARCHAR(191) NULL,
    ADD COLUMN `field6` VARCHAR(191) NULL,
    ADD COLUMN `field7` VARCHAR(191) NULL,
    ADD COLUMN `field8` VARCHAR(191) NULL,
    ADD COLUMN `field9` VARCHAR(191) NULL;
